spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stoom_addressbook_db
      username: addressbook
      password: addressbook

integration:
  services:
    google-maps:
      apikey: ${GOOGLE_MAPS_API_KEY}